### ISSUE TITLE
Is it possible to use free server provided from github?

### ISSUE THREAD

**Issue by leekichang** [starmin114/YonseiMapAllInOne#1]
Do this project needs the AWS server that we are currently using...? If it is a static web, I think it would be fine... Can you check that out sung min...?

**Comment by sungminlee114** [comment]
@leekichang Smart idea.

Currently on the backside of this service, there is a DB running and it is mainly for sake of offering "easy data modifying tool leveraging admin page" to those who are not expert in programming.

It was a necessary choice at the development state where numerous queries have to be applied. Since we are at the deployment state, there isn't any complicated queries now, and we can formulate this DB to static datas and run the server static.

But, at the end of our years we decided not to do so because:
1. This requires efforts which is not negligible.
2. Considering further developments on this project, say, mobile app, complexity of backend tasks will grow and eventually it will fallback again to non static server.

Is this a satisfying answer?

--

But still I welcome if you start on the "formulating" work. 😁😁

**Comment by leekichang** [comment]
Thx for detail explanation about my question. To be honest I just wanted to use the github issue 🥲 anyway... buy me coffee when you coming back from the Starbucks
